# Generated by Django 3.0.6 on 2020-05-06 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercisesapp', '0002_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercisesapp.Cohort'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='slack_handle',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='specialty',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
